apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-noprod2-service1
  namespace: app2-noprod2
  labels:
    app: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: main
        image: quay.io/gsciorti/openshift4/ose-hello-openshift-rhel8
        ports:
        - containerPort: 8080
