apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-noprod1-service3
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io # Cancella i pod se cancelli la App
spec:
  project: default
  source:
    repoURL: 'https://github.com/giovannisciortino/acm_appset_app2.git'
    targetRevision: noprod1
    path: workloads/service3  # Punta al deployment reale
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app2-noprod1   # Il namespace di destinazione richiesto
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true    # Crea il namespace app2-noprod1 se non esiste
