apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-noprod3-service2
  namespace: app2-noprod3
  labels:
    app: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: main
        image: quay.io/gsciorti/openshift4/ose-hello-openshift-rhel8
        ports:
        - containerPort: 8080
